export interface Doc_AnexosHv {
    COPIA_REGISTRO_SANITARIO: string;
    COPIA_REGISTRO_IMPORTACION: string;
    COPIA_PMISO_COMERCIALIZACION: string;
    COPIA_FACTURA: string;
    COPIA_INGRESO_ALMACEN: string;
    CP_RBO_SATISFACCION_PRESTADOR: string;
    CP_RBO_SATISFACCION_OPERADOR: string;
    CAPACION_TEC_ASISTENCIAL: string;
    HOJA_VIDA_PERSONAL_TECNICO: string;
    CERT_CALIB_VALID_CALPERSONAL: string;
    RNES_FABRICANTE_CALIBRACION: string;
    GUIA_RAPIDA_OPERACION: string;
    RNES_FABRICANTE_ACEOS_CBLES: string;
    PROTOCOLO_PROVEEDOR: string;
    CRONOGRAMA_MANTENIMIENTO_T_G: string;
    OBSERVACIONES: string;


}
